### ISSUE TITLE
Transfer general Instances.v lemma to Stdlib

### ISSUE THREAD

**Issue by palmskog** [coq-community/aac-tactics#123]
The [following lemma](https://github.com/coq-community/aac-tactics/blob/96e0d5cd08d0fe498baffd04b825f24209041938/theories/Instances.v#L160-L162) should be transferred to Coq's Stdlib:
```coq
  Lemma Pmult_1_l (x : positive) : 1 * x = x.
  Proof. reflexivity. Qed.
```

**Comment by SkySkimmer** [comment]
>aac_append_Proper

What is this good for? 
~~~coq
Require Import Morphisms List.

Type fun A => _ : Proper (eq ==> eq ==> eq) (@app A).
~~~
already succeeds

**Comment by palmskog** [comment]
OK, let's skip the `Proper` lemma then.
