### ISSUE TITLE
README update

### ISSUE THREAD

**Issue by palmskog** [coq-community/aac-tactics#17]
I think the current README file is in need of an update, for example:

- does not use Markdown syntax
- does not mention the namespace of the plugin (`AAC_tactics`)
- does not give a small example
- does not explain manual building and installation
- does not link to the paper describing the underlying theory and implementation

@fakusb does an update like this sound good to you?

**Comment by Zimmi48** [comment]
@palmskog @fakusb I suggest starting with the template that can be found in https://github.com/coq-community/manifesto/tree/master/templates
