### ISSUE TITLE
Tag for Coq 8.12.0

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq-community/aac-tactics#64]
I am currently preparing the Coq platform 8.12.0.

In order to include aac-tactics as planned, I need a tagged release of aac-tactics and an opam package.

I confirmed that the latest commit of the v8.12 branch, that is "ba10dce9877626608ccdf67daee6852b4d896ac0" works. As far as I can tell this is also what is in the Windows installer of Coq 8.12.0. So I would suggest to release this as V8.12.

**Comment by palmskog** [comment]
Sure. I will use the usual convention and name the tag `v8.12.0` though.

**Comment by MSoegtropIMC** [comment]
> Sure. I will use the usual convention and name the tag `v8.12.0` though.

Perfect thanks! I don't care what the name of the tag is, as long as it somehow looks like a release tag.

**Comment by palmskog** [comment]
Here is the release: https://github.com/coq-community/aac-tactics/releases/tag/v8.12.0

Note that this uses a later commit (4f8d29e862b89037dcd721192ffb64a9fc88a983) than the one you indicated above, since I did some final metadata tweaking on the `v8.12` branch.

**Comment by MSoegtropIMC** [comment]
> Note that this uses a later commit (4f8d29e) than the one you indicated above, since I did some final metadata tweaking on the v8.12 branch.

That's fine - I don't think we need to be 100% compatible to the 8.12.0 windows installer since there will also be a platform installer.
