### ISSUE TITLE
Please create a tag for the upcoming release of Coq 8.13

### ISSUE THREAD

**Issue by gares** [coq-community/aac-tactics#69]
The Coq team is planning to release Coq 8.13-beta1 on December 7, 2020
and Coq 8.13.0 on January 7, 2020.

Your project is currently scheduled for being bundled in the Windows installer.

We are currently testing commit 0739fe9b002aaec26ca77a2c7ea0e68f3e6b2012
on branch https://github.com/coq-community/aac-tactics/tree/master
but we would like to ship a released version instead (a tag in git's slang).

Could you please tag that commit, or communicate us any other tag
that works with the Coq branch v8.13 at the *latest* 15 days before the
date of the final release?

Thanks!

CC: https://github.com/coq/coq/issues/12334

**Comment by palmskog** [comment]
@gares I have now created the tag `v8.13.0` (https://github.com/coq-community/aac-tactics/releases/tag/v8.13.0) which is compatible with 8.13+beta1, so closing this.

**Comment by gares** [comment]
great thanks!
