### ISSUE TITLE
Please create a tag for the upcoming release of Coq 8.14

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq-community/aac-tactics#87]
The Coq team released Coq 8.14+rc1 on September 17, 2021
and plans to release Coq 8.14.0 before October 31, 2021.
A corresponding Coq Platform releases should be released before November 30, 2021.
It can be dealyed in case of difficulties until January 31, 2022, but this should be an exception.

Coq CI is currently testing commit 16d30aba89ec4f5a7663ff31ac1b81212dd22e9a
on branch https://github.com/coq-community/aac-tactics/tree/master
but we would like to ship a released version instead (a tag in git's slang).

Coq Platform is currently *not testing* this package!

Could you please create a tag, or communicate us any existing tag that works with
Coq branch v8.14, preferably 15 days before November 30, 2021
or earlier? In case we might have to delay the Coq Platform release cause of issues with
your project, we would prefer to be informed about the situation as early as possible.

Thanks!

P.S.: this issue has been creates semi-automatically.

CC: https://github.com/coq/platform/issues/139

**Comment by palmskog** [comment]
I have now created the tag v8.14.0 (https://github.com/coq-community/aac-tactics/releases/tag/v8.14.0) which is known to be compatible with 8.14+rc1.

Here is the opam file: https://github.com/coq/opam-coq-archive/blob/93b645e8642f0b4461e376ebdb8ab9124a3e74d4/extra-dev/packages/coq-aac-tactics/coq-aac-tactics.8.14.0/opam

**Comment by MSoegtropIMC** [comment]
@palmskog : thanks! I just wonder why the opam package is in extra-dev. If you don't plan to change it for 8.14.0 I don't see a good reason for not publishing it as a release package. See e.g. (https://github.com/coq/opam-coq-archive/blob/master/released/packages/coq-mathcomp-ssreflect/coq-mathcomp-ssreflect.1.12.0/opam) which also already has a 8.14 compatible package in `released`.

**Comment by palmskog** [comment]
Putting the package in `released` without a corresponding released Coq version the regular OCaml opam repo requires a radical restructuring of how we have handled betas and release candidates so far in the Coq opam repo. I think this should have been discussed beforehand. Looking through CEP 52, I don't see any mention of this.

@gares can you clarify what your intention was here? I thought we were going to handle pre-release packages just the same as last time.

**Comment by MSoegtropIMC** [comment]
Yes, I have seen the issue in my PR for bignums 8.14. I didn't see the problem before.

I guess it is reasonable then to put all packages which require 8.14 (or have an 8.14 in their version name) into `extra-dev` until 8.14.0 is released and then we do one PR to move over all such packages to `released`

Updated packages which are compatible with a range of Coq versions (e.g. mathcomp) can of course go immediately into `released`. This applies only to packages which require Coq 8.14.

**Comment by MSoegtropIMC** [comment]
I just saw that there is a new tag v8.14.1 - shall I use this tag for Coq Platform 2021.11?

**Comment by MSoegtropIMC** [comment]
I found an answer in https://github.com/coq/opam-coq-archive/pull/1853 ... so I will use v8.14.1 for Coq Platform 2021.11.
