### ISSUE TITLE
Support for idempotent operations

### ISSUE THREAD

**Issue by damien-pous** [coq-community/aac-tactics#90]
Commit 082ed3cc71 in branch v8.13 adds support for idempotent operations.
How show we integrate this into the various branches / coq version?

**Comment by damien-pous** [comment]
>
>
> Thanks for opening the issue @damien-pous <https://github.com/damien-pous>.
> I agree idempotence is a valuable feature, and there is no need to revert
> anything. Moreover, I can take care of updating the 8.13.2 release (and
> merge the package to the opam archive) once we reach some fixpoint in the
> discussion.
>
ok

> I propose the following plan:
>
>    - For the v8.13 branch, all that is needed is to update the
>    documentation to mention idempotence. What I think would be really nice to
>    include (but not mandatory), is some small example (3-10 lines) using
>    idempotence for the README. Do you maybe have some small example like that?
>
> I did include an example in Tutorial.v, I can add something in the README,
but for now it's rather minimalistic (a single example with an AC
operation) and it points to Tutorial.v for more examples.
Maybe I should just mention idempotency in the README and elaborate a bit
more in Tutorial.v ?
I'll do that for now.
-> with a pull request or a second commit in 8.13?


>    - We urgently need to port the idempotence to the v8.14 branch and
>    make a corresponding release for Coq 8.14 (even though only 8.14+rc1 is out
>    currently). Is this something you could take a look at @damien-pous
>    <https://github.com/damien-pous>? If so, you can make a pull request
>    with that targeting the v8.14 branch. It may work to just cherry-pick
>    the commit 74899ac
>    <https://github.com/coq-community/aac-tactics/commit/74899ac445cbdf71c64f819dbd38f212b7af1caf>
>    in that branch and go from there.
>
> ok, I'll try to do that now.

>
>    - We need to port idempotence to master, but this is less urgent. This
>    is something I could do after the 8.13 and 8.14 releases done.
>
> Does this sound reasonable?
>
yes, thanks !

**Comment by damien-pous** [comment]
I've done a PR on branch v8.14, which seems to compile fine according to the CI.
It contains a cherry pick of commit 74899ac, as well as another commit adding some more documentation.

I can either push this second commit to v8.13, or turn it into another PR. As you prefer @palmskog.

**Comment by palmskog** [comment]
Releases are now done and merged in the Coq opam archive, and the idempotence changes and documentation updates have been applied to the `master` branch, so let's close this.

@damien-pous to help us promote AAC Tactics to Coq users, we would appreciate if you update the link on your website to go to https://github.com/coq-community/aac-tactics (same goes for other projects in Coq-community such as graph-theory)

**Comment by damien-pous** [comment]
@palmskog : I updated the link to aac-tactics...
Thanks for everything, once again!
